{ config, lib, pkgs, ... }:

with lib; with ns config ./.; {

  # works with wayland (sorta)

  options = opt {
    enable = mkEnableOption "home impermanence";
  };

  config = mkIf cfg.enable {
    # override to add grim
    systemd.user.services.xscreensaver.Service.Environment = mkForce [ "PATH=${makeBinPath [ pkgs.xscreensaver pkgs.grim ]}" ];

    services.xscreensaver = {
      enable = true;
      package = pkgs.xscreensaver; # ensure unstable, version 6.11 minimum!
      settings = {
        lock = false; # not working in wayland
        grabDesktopImages = false;
        fade = false;
        unfade = false;
        dpmsEnabled = false;

        timeout = "0:10:00";
        cycle = "0:10:00";
        mode = "random";

        textMode = "program";
        textProgram = "${pkgs.fortune}/bin/fortune";

        programs = pipe [
          "abstractile"
          "anemone"
          "- anemotaxis"
          "- GL: antinspect"
          "- GL: antmaze"
          "- GL: antspotlight"
          "- apollonian"
          "- apple2"
          "- GL: atlantis"
          "attraction"
          "GL: atunnel"
          "barcode"
          "GL: beats"
          "binaryhorizon"
          "binaryring"
          "blaster"
          "GL: blinkbox"
          "- blitspin"
          "GL: blocktube"
          "GL: boing"
          "bouboule"
          "GL: bouncingcow"
          "GL: boxed"
          "boxfit"
          "- braid"
          "- bsod"
          "- GL: bubble3d"
          "- bumps"
          "GL: cage"
          "- GL: carousel"
          "ccurve"
          "- celtic"
          "GL: chompytower"
          "GL: circuit"
          "GL: cityflow"
          "cloudlife"
          "- GL: companioncube"
          "- compass"
          "coral"
          "GL: covid19"
          "GL: crackberg"
          "GL: crumbler"
          "- crystal"
          "GL: cube21"
          "GL: cubenetic"
          "GL: cubestack"
          "GL: cubestorm"
          "GL: cubetwist"
          "GL: cubicgrid"
          "- GL: cubocteversion"
          "cwaves"
          "cynosure"
          "- GL: dangerball"
          "- decayscreen"
          "- deco"
          "GL: deepstars"
          "- deluxe"
          "- demon"
          "GL: discoball"
          "discrete"
          "- distort"
          "- GL: dnalogo"
          "drift"
          "- droste"
          "GL: dumpsterfire"
          "GL: dymaxionmap"
          "- GL: endgame"
          "GL: energystream"
          "GL: engine"
          "epicycle"
          "eruption"
          "- GL: esper"
          "GL: etruscanvenus"
          "euler2d"
          "GL: extrusion"
          "- fadeplot"
          "fiberlamp"
          "- filmleader"
          "- fireworkx"
          "flame"
          "- GL: flipflop"
          "- GL: flipscreen3d"
          "- GL: fliptext"
          "flow"
          "fluidballs"
          "GL: flurry"
          "GL: flyingtoasters"
          "- fontglide"
          "fuzzyflakes"
          "galaxy"
          "GL: gears"
          "GL: geodesic"
          "GL: geodesicgears"
          "- GL: gflux"
          "GL: gibson"
          "- GL: glblur"
          "GL: glcells"
          "GL: gleidescope"
          "- GL: glhanoi"
          "- glitchpeg"
          "GL: glknots"
          "GL: glmatrix"
          "GL: glplanet"
          "GL: glschool"
          "- GL: glslideshow"
          "GL: glsnake"
          "- GL: gltext"
          "goop"
          "grav"
          "GL: gravitywell"
          "greynetic"
          "halftone"
          "halo"
          "- GL: handsy"
          "- GL: headroom"
          "helix"
          "hexadrop" # CHECKED UP TO HERE!
          "GL: hexstrut"
          "GL: hextrail"
          "GL: highvoltage"
          "GL: hilbert"
          "hopalong"
          "GL: hopffibration"
          "GL: hydrostat"
          "GL: hypertorus"
          "GL: hypnowheel"
          "ifs"
          "imsmap"
          "interaggregate"
          "interference"
          "intermomentary"
          "- GL: jigglypuff"
          "GL: jigsaw"
          "GL: juggler3d"
          "julia"
          "- kaleidescope"
          "GL: kaleidocycle"
          "GL: kallisti"
          "GL: klein"
          "GL: klondike"
          "kumppa"
          "GL: lament"
          "GL: lavalite"
          "- lcdscrub"
          "GL: lockward"
          "- loop"
          "m6502"
          "GL: mapscroller"
          "marbling"
          "maze"
          "GL: maze3d"
          "memscroller"
          "GL: menger"
          "metaballs"
          "GL: mirrorblob"
          "GL: moebius"
          "GL: moebiusgears"
          "moire"
          "moire2"
          "GL: molecule"
          "GL: morph3d"
          "mountain"
          "munch"
          "GL: nakagin"
          "- nerverot"
          "GL: noof"
          "noseguy"
          "pacman"
          "GL: papercube"
          "pedal"
          "GL: peepers"
          "penetrate"
          "penrose"
          "petri"
          "phosphor"
          "GL: photopile"
          "piecewise"
          "GL: pinion"
          "GL: pipes"
          "GL: platonicfolding"
          "GL: polyhedra"
          "- polyominoes"
          "GL: polytopes"
          "pong"
          "popsquares"
          "GL: projectiveplane"
          "- GL: providence"
          "GL: pulsar"
          "- pyro"
          "qix"
          "GL: quasicrystal"
          "GL: queens"
          "GL: raverhoop"
          "GL: razzledazzle"
          "rdbomb"
          "ripples"
          "- rocks"
          "GL: romanboy"
          "rorschach"
          "rotzoomer"
          "GL: rubik"
          "GL: rubikblocks"
          "- GL: sballs"
          "scooter"
          "shadebobs"
          "- sierpinski"
          "GL: sierpinski3d"
          "GL: skulloop"
          "GL: skytentacles"
          "slidescreen"
          "slip"
          "GL: sonar"
          "speedmine"
          "GL: sphereeversion"
          "GL: spheremonics"
          "GL: splitflap"
          "GL: splodesic"
          "spotlight"
          "GL: sproingies"
          "squiral"
          "GL: squirtorus"
          "GL: stairs"
          "starfish"
          "GL: starwars"
          "GL: stonerview"
          "strange"
          "substrate"
          "GL: superquadrics"
          "GL: surfaces"
          "swirl"
          "GL: tangram"
          "tessellimage"
          "GL: timetunnel"
          "GL: topblock"
          "triangle"
          "GL: tronbit"
          "truchet"
          "twang"
          "GL: unicrud"
          "GL: unknownpleasures"
          "vermiculate"
          "vfeedback"
          "- vidwhacker"
          "GL: vigilance"
          "GL: voronoi"
          "wander"
          "- webcollage"
          "whirlwindwarp"
          "GL: winduprobot"
          "wormhole"
          "xanalogtv"
          "xflame"
          "xjack"
          "xlyap"
          "xmatrix"
          "xrayswarm"
          "xspirograph"
          "zoom"
        ] [
          (map (x: "${x} --root \\n\\"))
          concatLines
        ];
      };
    };
  };
}
